name: Run Selenium Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup .NET
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: '8.0.x'

          - name: Install Chrome
            run: |
                sudo apt update
                sudo apt install -y google-chrome-stable
                CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+")
                echo "Using Chrome version: $CHROME_VERSION"
                wget -q https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
                unzip chromedriver_linux64.zip
                sudo mv chromedriver /usr/local/bin/
                sudo chmod +x /usr/local/bin/chromedriver

          - name: Restore dependecies
            run: dotnet restore

          - name: Run Selenium Tests
            run: dotnet test